#!/bin/bash
source ./0-configure.sh
cd $QMULE_BUILD_ROOT/qmule-deps
BOOST_DIR=`ls -1 | grep boost`
LIBTORRENT_DIR=`ls -1 | grep torrent`
export QMULE_BOOST_ROOT=$QMULE_BUILD_ROOT/qmule-deps/$BOOST_DIR
export QMULE_LIBTORRENT_ROOT=$QMULE_BUILD_ROOT/qmule-deps/$LIBTORRENT_DIR
export QMULE_LIBED2K_ROOT=$QMULE_BUILD_ROOT/libed2k
export QMULE_BOOST_BUILD_DIR=$QMULE_BUILD_CONFIG/tmp
export QMULE_BOOST_INSTALL_DIR=$QMULE_BUILD_CONFIG/lib
export QMULE_LIBTORRENT_INSTALL_DIR=$QMULE_BUILD_CONFIG/lib
cd $QMULE_BUILD_CONFIG
