#!/bin/bash
source ./2-configure.sh

QMULE_ROOT=$QMULE_BUILD_ROOT/qmule

export BOOST_ROOT=$QMULE_BOOST_INSTALL_DIR
export LIBED2K_ROOT=$QMULE_LIBED2K_ROOT
export LIBTORRENT_ROOT=$QMULE_LIBTORRENT_INSTALL_DIR
export PKG_CONFIG_PATH=$QMULE_LIBTORRENT_INSTALL_DIR/lib/pkgconfig

cd $QMULE_ROOT

git checkout linux-build
qmake && make -j$QMULE_BUILD_JOBS
cp $QMULE_ROOT/src/qmule $QMULE_BUILD_CONFIG/bin

cd $QMULE_BUILD_CONFIG

unset BOOST_ROOT
unset LIBED2K_ROOT
unset LIBTORRENT_ROOT
unset PKG_CONFIG_PATH
